source("scripts/graficos.R")

ggsave("figures/torcao_impacto.png", tor.imp)
ggsave("figures/painel_AlfTor_imp_grupo.png", alftor.imp.grupo)
ggsave("figures/painel_AlfTor_global.png", alftor.global)
ggsave("figures/painel_AlfTor_grupo.png", alftor.grupo)
ggsave("figures/painel_AlfTor_grupo_imp.png", alftor.grupo.imp)
ggsave("figures/painel_AlfTor_grupo_imp_full.png", alftor.grupo.imp.full)
ggsave("figures/painel_sex_grupo.png", bar.imp.sex.grupo)
ggsave("figures/impacto_freq.png", bar.imp)
