prop.table(table(dados$SEXO))
library(Hmisc)
describe(dados)
with(dados, cor.test(`TORÇÃO D`, `ALFA D`))
with(dados, cor.test(`TORÇÃO E`, `ALFA E`))
lm(`TORÇÃO D` ~ `ALFA D` + `LADO DOR`, data = dados)
summary(lm(`TORÇÃO D` ~ `ALFA D` + `LADO DOR`, data = dados))
with(dados, boxplot(`ALFA D` ~ `LADO DOR`, main = "ALFA D x LADO DOR"))
with(dados, boxplot(`ALFA E` ~ `LADO DOR`, main = "ALFA E x LADO DOR"))
with(dados, boxplot(`TORÇÃO D` ~ `LADO DOR`, main = "TORÇÃO D x LADO DOR"))
with(dados, boxplot(`TORÇÃO E` ~ `LADO DOR`, main = "TORÇÃO E x LADO DOR"))
