prop.table(table(dados$SEXO))
library(Hmisc)
describe(dados)
with(dados, cor.test(`TORCAO D`, `ALFA D`))
with(dados, cor.test(`TORCAO E`, `ALFA E`))
lm(`TORCAO D` ~ `ALFA D` + `LADO DOR`, data = dados)
summary(lm(`TORCAO D` ~ `ALFA D` + `LADO DOR`, data = dados))
with(dados, boxplot(`ALFA D` ~ `LADO DOR`, main = "ALFA D x LADO DOR"))
with(dados, boxplot(`ALFA E` ~ `LADO DOR`, main = "ALFA E x LADO DOR"))
with(dados, boxplot(`TORCAO D` ~ `LADO DOR`, main = "TORCAO D x LADO DOR"))
with(dados, boxplot(`TORCAO E` ~ `LADO DOR`, main = "TORCAO E x LADO DOR"))
